### PR TITLE
Add copyright to footer

### PR DESCRIPTION
**Pull request by Healthedata1**
added boston children's to footer for copyright.  and CC + BY link.  see

http://build.fhir.org/ig/Healthedata1/smart-app-launch-viewer/index.html

### CODE REVIEW

**Comment by jmandel** [comment]
I think you want to make this a PR into the smart-app-launch master branch. I can help work through the mechanics, but the basic approach would be:

1. Merge the master branch into your "Healthedata1:add-copyright-to-footer" branch so you're building on top of the latest already-merged changes

2. Create a Pull Request asking to merge "Healthedata1:add-copyright-to-footer" into "HL7/smart-app-launch:master".

**Comment by Healthedata1** [comment]
Yes I didn't intend to PR all the previous commits.  Do you want to reject this and I redo it.

**Comment by jmandel** [comment]
No need to reject; if you fix up the commit history per the advice above, that should "salvage" it. Let me know if you need help working through this.

**Comment by Healthedata1** [comment]
I created a new PR with just the changes. I think I have the workflow figured out now.

**Comment by jmandel** [comment]
Obviated by #205.

**Pull request closed without merging**
