### PR TITLE
Offline access

### PR DESCRIPTION
**Pull request by Healthedata1**
offline_access  Ballot#3, part of Ballot#44, Ballot#54, Ballot#63, Ballot#74, Ballot#119, Ballot#147, Ballot#202,  #8,#195, #144, #123, #79,#67, #58, #48

### CODE REVIEW

**Comment by lcmaas** [comment]
This statement as updated by the last commit is inaccurate: "After an access token expires, the app requests a refresh token via the `offline_access` scope (see <a href="scopes-and-launch-context/index.html">SMART on FHIR Access Scopes</a> for details) and the EHR supplies a `refresh_token` in the authorization response."

May I suggest the following:

The app requests a refresh token in its authorization request via the `offline_access` scope (see <a href="scopes-and-launch-context/index.html">SMART on FHIR Access Scopes</a> for details) and (if granted) the EHR supplies a `refresh_token` in the token response.  After an access token expires, the app requests a new access token by providing its refresh token to the EHR's token endpoint.

**Comment by jmandel** [comment]
Indeed, thanks @lcmaas!  @Healthedata1 can you please update per Luis's suggestion?

**Comment by jmandel** [comment]
Given changes coming in #228, let's merge/land this first, and then adjust #228 to fit (i.e. we'll want to expand @lcmaas's suggested language to include `online_access` as well --- but let's do that in #228.

**Comment by jmandel** [comment]
All right -- if it's easier, feel free in implement both changes in #228 and close out this issue in favor of that's one.

**Comment by Healthedata1** [comment]
OK

**Pull request closed without merging**
